In [45]:
%matplotlib notebook
from matplotlib import pylab as plt
#from ipywidgets import interact
#from IPython import display
from collections import deque
import numpy as np

In [46]:
from IPython.display import IFrame
import ipywidgets as widgets

In [47]:
import os
import sys
sys.path.append(os.path.join(os.path.abspath(os.path.dirname('__file__')), '..', 'software_installation'))
sys.path.append(os.path.join(os.path.abspath(os.path.dirname('__file__')), '..', 'joint_control'))
sys.path.append(os.path.join(os.path.abspath(os.path.dirname('__file__')), '..', 'distributed_computing'))
sys.path.append(os.path.join(os.path.abspath(os.path.dirname('__file__')), '..', 'introduction'))
sys.path.append(os.path.join(os.path.abspath(os.path.dirname('__file__')), '..', 'kinematics'))

In [48]:
from inverse_kinematics import InverseKinematicsAgent

In [49]:
from keyframes import *

In [50]:
agent = InverseKinematicsAgent()
agent.start()

In [51]:
#agent.joint_names

In [52]:
#agent.__dict__
#dir(agent)

In [53]:
#agent.target_joints

In [54]:
#agent.transforms

In [55]:
import json
from ipywidgets import interact
new_text = ""

In [56]:
def set_joint_target(value, joint):
    agent.target_joints[joint] = value
    sliders = value    

def saveData(b):
    with open(f'Data/{new_text}.json', 'w') as outfile:
        data = {}
        for key in dict.keys(agent.target_joints):
            data[key] = float(agent.target_joints[key])
        json.dump(data, outfile)
        
    with output:
        print(f'{new_text}.json generated')
        
def set_text(change):
    with output2:
        global new_text 
        new_text = change['new']

In [57]:
for joint in agent.target_joints:
    s = widgets.FloatSlider(value=0,min=-1,max=1,step=0.01,description=joint)
    t = interact(set_joint_target, value=s, joint=joint)
    
    
text = widgets.Text(description="File Name")
output2 = widgets.Output()

text.observe(set_text, names='value')
    
button = widgets.Button(description="Save Data")
output = widgets.Output()

display(text, button, output)
button.on_click(saveData)




interactive(children=(FloatSlider(value=0.0, description='HeadYaw', max=1.0, min=-1.0, step=0.01), Text(value=…

interactive(children=(FloatSlider(value=0.0, description='HeadPitch', max=1.0, min=-1.0, step=0.01), Text(valu…

interactive(children=(FloatSlider(value=0.0, description='LShoulderPitch', max=1.0, min=-1.0, step=0.01), Text…

interactive(children=(FloatSlider(value=0.0, description='LShoulderRoll', max=1.0, min=-1.0, step=0.01), Text(…

interactive(children=(FloatSlider(value=0.0, description='LElbowYaw', max=1.0, min=-1.0, step=0.01), Text(valu…

interactive(children=(FloatSlider(value=0.0, description='LElbowRoll', max=1.0, min=-1.0, step=0.01), Text(val…

interactive(children=(FloatSlider(value=0.0, description='LHipYawPitch', max=1.0, min=-1.0, step=0.01), Text(v…

interactive(children=(FloatSlider(value=0.0, description='LHipRoll', max=1.0, min=-1.0, step=0.01), Text(value…

interactive(children=(FloatSlider(value=0.0, description='LHipPitch', max=1.0, min=-1.0, step=0.01), Text(valu…

interactive(children=(FloatSlider(value=0.0, description='LKneePitch', max=1.0, min=-1.0, step=0.01), Text(val…

interactive(children=(FloatSlider(value=0.0, description='LAnklePitch', max=1.0, min=-1.0, step=0.01), Text(va…

interactive(children=(FloatSlider(value=0.0, description='LAnkleRoll', max=1.0, min=-1.0, step=0.01), Text(val…

interactive(children=(FloatSlider(value=0.0, description='RShoulderPitch', max=1.0, min=-1.0, step=0.01), Text…

interactive(children=(FloatSlider(value=0.0, description='RShoulderRoll', max=1.0, min=-1.0, step=0.01), Text(…

interactive(children=(FloatSlider(value=0.0, description='RElbowYaw', max=1.0, min=-1.0, step=0.01), Text(valu…

interactive(children=(FloatSlider(value=0.0, description='RElbowRoll', max=1.0, min=-1.0, step=0.01), Text(val…

interactive(children=(FloatSlider(value=0.0, description='RHipYawPitch', max=1.0, min=-1.0, step=0.01), Text(v…

interactive(children=(FloatSlider(value=0.0, description='RHipRoll', max=1.0, min=-1.0, step=0.01), Text(value…

interactive(children=(FloatSlider(value=0.0, description='RHipPitch', max=1.0, min=-1.0, step=0.01), Text(valu…

interactive(children=(FloatSlider(value=0.0, description='RKneePitch', max=1.0, min=-1.0, step=0.01), Text(val…

interactive(children=(FloatSlider(value=0.0, description='RAnklePitch', max=1.0, min=-1.0, step=0.01), Text(va…

interactive(children=(FloatSlider(value=0.0, description='RAnkleRoll', max=1.0, min=-1.0, step=0.01), Text(val…

Text(value='', description='File Name')

Button(description='Save Data', style=ButtonStyle())

Output()

In [58]:
#agent.perception.__dict__

In [59]:
#agent.keyframes = rightBackToStand()
#agent.keyframes = rightBackToStand()
#agent.keyframes = rightBackToStand()
#agent.keyframes = rightBackToStand()
#agent.keyframes = rightBackToStand()
agent.keyframes = ([],[],[])

In [60]:
wipeKF = wipe_forehead(0)
angles = [row[0] for row in wipeKF[2][0]]
angles

[-0.02612, 0.42794, 0.30829, 0.11194, -0.01385, 0.06132]

In [61]:
wipeKF[0][0],wipeKF[1][0],wipeKF[2][0]

('HeadPitch',
 [0.96, 1.68, 3.28, 3.96, 4.52, 5.08],
 [[-0.02612, [3, -0.32, 0.0], [3, 0.24, 0.0]],
  [0.42794, [3, -0.24, 0.0], [3, 0.53333, 0.0]],
  [0.30829, [3, -0.53333, 0.07392], [3, 0.22667, -0.03142]],
  [0.11194, [3, -0.22667, 0.05889], [3, 0.18667, -0.04849]],
  [-0.01385, [3, -0.18667, 0.0], [3, 0.18667, 0.0]],
  [0.06132, [3, -0.18667, 0.0], [3, 0.0, 0.0]]])

In [62]:
len(wipeKF[2][6])

6

In [63]:
#agent.target_joints

In [64]:
#dict.keys(agent.target_joints)

In [65]:
def generateKeyframe():
    names = []
    time = np.linspace(0, 5.2, 6, endpoint=True)
    joints = []
    angle = [[-1,[0.2,0.0],[0.2,0.0]],[-0.4,[0.2,0.0],[0.2,0.0]],[-1,[0.2,0.0],[0.2,0.0]],[-0.6,[0.2,0.0],[0.2,0.0]],[0,[0.2,0.0],[0.2,0.0]],[0.6,[0.2,0.0],[0.2,0.0]]]
                                                                                                               
    for key in dict.keys(agent.target_joints):
        names.append(key)
        
    for i in range(len(names)):
        joint=[]
        for j in range(len(time)):
            joint.append([0,[0.2,0.0],[0.2,0.0]])
        if i==2:
            joints.append([[-1,[]],[-0.4,[]],[-1,[]],[-0.6,[]], [0,[]],[0.6,[]] ])
        else:
            joints.append(angle)
            
    times = []
    for i in range(len(names)):
        times.append(time)
        
            
    return (names,times,joints)
        
kf =generateKeyframe()
kf

(['HeadYaw',
  'HeadPitch',
  'LShoulderPitch',
  'LShoulderRoll',
  'LElbowYaw',
  'LElbowRoll',
  'LHipYawPitch',
  'LHipRoll',
  'LHipPitch',
  'LKneePitch',
  'LAnklePitch',
  'LAnkleRoll',
  'RShoulderPitch',
  'RShoulderRoll',
  'RElbowYaw',
  'RElbowRoll',
  'RHipYawPitch',
  'RHipRoll',
  'RHipPitch',
  'RKneePitch',
  'RAnklePitch',
  'RAnkleRoll'],
 [array([0.  , 1.04, 2.08, 3.12, 4.16, 5.2 ]),
  array([0.  , 1.04, 2.08, 3.12, 4.16, 5.2 ]),
  array([0.  , 1.04, 2.08, 3.12, 4.16, 5.2 ]),
  array([0.  , 1.04, 2.08, 3.12, 4.16, 5.2 ]),
  array([0.  , 1.04, 2.08, 3.12, 4.16, 5.2 ]),
  array([0.  , 1.04, 2.08, 3.12, 4.16, 5.2 ]),
  array([0.  , 1.04, 2.08, 3.12, 4.16, 5.2 ]),
  array([0.  , 1.04, 2.08, 3.12, 4.16, 5.2 ]),
  array([0.  , 1.04, 2.08, 3.12, 4.16, 5.2 ]),
  array([0.  , 1.04, 2.08, 3.12, 4.16, 5.2 ]),
  array([0.  , 1.04, 2.08, 3.12, 4.16, 5.2 ]),
  array([0.  , 1.04, 2.08, 3.12, 4.16, 5.2 ]),
  array([0.  , 1.04, 2.08, 3.12, 4.16, 5.2 ]),
  array([0.  , 1.04, 2.08, 3

In [66]:
#agent.keyframes = kf